name: example
version: 1.0.0
description: >-
  An example for similo.
author: Yunus Gungor <yunusgnr@gmail.com>
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  similo_annotations: ^1.0.3
dev_dependencies:
  similo: ^1.0.3
  build_runner: ^1.0.0