name: similo_annotations
description: Annotations package for similo
version: 1.0.3
author: Yunus Gungor <yunusgnr@gmail.com>
homepage: https://github.com/ynsgnr/similo

environment:  
  sdk: ">=2.0.0 <3.0.0"
  
dependencies:

dev_dependencies: