name: similo
description: Dart Builder for const constructors and copyWith
version: 1.0.0
author: Yunus Gungor <yunusgnr@gmail.com>
homepage: https://github.com/ynsngr/similo

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:  
  build: ^1.1.6  
  source_gen: ^0.9.0  
  similo_annotations:    
    path: ../similo_annotations/
    
dev_dependencies:  
  build_test: ^0.10.0  
  build_runner: ^1.6.6
  test: ^1.0.0