name: similo
description: Dart Builder for const constructors and copyWith
version: 1.0.3
author: Yunus Gungor <yunusgnr@gmail.com>
homepage: https://github.com/ynsgnr/similo

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:  
  build: ^1.1.6  
  source_gen: ^0.9.0
  similo_annotations: ^1.0.3
  analyzer: ^0.38.2
    
dev_dependencies:  
  build_test: ^0.10.0  
  build_runner: ^1.0.0
  test: ^1.0.0
  source_gen_test: ^0.1.0